# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_employee_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
