# Generated by Codex on 2026-05-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_account_requires_password_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mention', 'Mention'), ('status', 'Status update'), ('comment', 'Comment')], default='comment', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('mention_label', models.CharField(blank=True, max_length=120)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_employee_ticket_notifications', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.employeeticketcomment')),
                ('recipient_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notifications', to='account.employeeprofile')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_ticket_notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.employeeticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['recipient_user', 'is_read', 'created_at'], name='account_emp_rec_user_2080b0_idx'),
                    models.Index(fields=['recipient_employee', 'is_read', 'created_at'], name='account_emp_rec_emp_c7a4a4_idx'),
                    models.Index(fields=['ticket', 'created_at'], name='account_emp_ticket_c74979_idx'),
                ],
            },
        ),
    ]
