# Generated by Django 3.2.7 on 2026-05-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_ticket_comment_links_and_attachments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentCopy',
        ),
        migrations.RemoveField(
            model_name='edudegree',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='edudegree',
            name='degreename',
        ),
        migrations.RemoveField(
            model_name='edudegree',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='edudegree',
            name='marksheets',
        ),
        migrations.DeleteModel(
            name='FutureCustomerContacts',
        ),
        migrations.RemoveIndex(
            model_name='employeeticketnotification',
            name='account_emp_rec_user_2080b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeticketnotification',
            name='account_emp_rec_emp_c7a4a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeticketnotification',
            name='account_emp_ticket_c74979_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='account',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='account',
            name='educationDegrees',
        ),
        migrations.RemoveField(
            model_name='account',
            name='usertitle',
        ),
        migrations.RemoveField(
            model_name='account',
            name='usertype',
        ),
        migrations.AddIndex(
            model_name='employeeticketnotification',
            index=models.Index(fields=['recipient_user', 'is_read', 'created_at'], name='account_emp_recipie_e1fb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeticketnotification',
            index=models.Index(fields=['recipient_employee', 'is_read', 'created_at'], name='account_emp_recipie_b781b1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeticketnotification',
            index=models.Index(fields=['ticket', 'created_at'], name='account_emp_ticket__464dd2_idx'),
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='DegreeName',
        ),
        migrations.DeleteModel(
            name='EduDegree',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='MarkSheet',
        ),
        migrations.DeleteModel(
            name='UserTitle',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
